apiVersion: apps/v1
kind: Deployment
metadata:
  name: timescaledb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timescaledb
  template:
    metadata:
      labels:
        app: timescaledb
    spec:
      containers:
        - name: timescaledb
          image: timescale/timescaledb:latest-pg15
          env:
            - name: POSTGRES_USER
              value: "user"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_DB
              value: "timescaledb"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: timescale-pv
              mountPath: /var/lib/postgresql/data
            - name: init-scripts
              mountPath: /scripts
          lifecycle:
            postStart:
              exec:
                command:
                  [
                    "/bin/sh",
                    "-c",
                    "until pg_isready -U user; do sleep 1; done && psql -U user -d timescaledb -f /scripts/init.sql"
                  ]
      volumes:
        - name: timescale-pv
          emptyDir: {}
        - name: init-scripts
          configMap:
            name: timescaledb-init-scripts